language: ruby
rvm:
- 2.0.0
script: bundle exec thor spec
env:
  global:
    secure: vFFIwGRhDys/Pz20PE0QdyYpAL5nfqd8X2McHUl/v6CBjRlU6Yq/6ewZ5rLVIl+s0BJG2nucZRzyLvqYGe5kO1MfpndBDyHg1NstJalKN/dFFJ/ekFg9jqrHDC4Bzmjep9XWeiaUGJb3JVodyDDLlXJ65s3ZH3/NjShyINO5OVg=
